name: alpha_vantage_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
author: Jim Simon <jim.j.simon@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http_client: "^0.3.1"
  json_annotation: ^0.2.2
#  path: ^1.4.1

dev_dependencies:
  build_runner: "^0.7.13+1"
  json_serializable: "^0.4.0"
  test: ^0.12.0
